# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.3
 
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xms512M -Xmx2G
    
    steps:
      - checkout
      
      - run: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
        
      # run tests!
      - run: mvn --batch-mode test jacoco:report -t ci-toolchains.xml
      
      - run: bash <(curl -s https://codecov.io/bash)
      
      - run: sh src/main/config/countfiles.sh
  deployment:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.3

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xms512M -Xmx2G
    
    steps:
      - checkout
      
      - run: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
        
      # run deployment!
      - run: mvn --batch-mode deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml -t ci-toolchains.xml
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
